language: node_js

branches:
  only:
    - master

deploy:
  provider: firebase
  token:
    secure: TmxcYBT3ICAIi+hGRLQ+ApuKg+Rf9l5gXR6XzvUSkoKPQUgLsSQa0KqFm4k5NAwOIdJP8Y2hsfb1zy/F8/w2kRJgrMpKb7ffqj73szug7o19ucSSD5tUVDiKJYPq6muaRII1jwqtBjK7+6eKWaebwSdc3Lk5PRUBJFkeZ49miiWa8Sh8r293wl79Nwq1gg3HAlh0tznSjEeLimXzSdRLR5ERhgci02s63yy1uDodw4bvJSYalnu3AbZgJTGDsTywTxSgiW4F1uU0m7xpYWKb5AyIYGCxZ3JN+jhiV/CM6PdRdo5/iOuD7D7q8lKHpw15QRabmCE/8keRpkPhLJKAZNkhSBTuz8pjAo10vOfl1tNp4vZcMYqPDljpS8gWZkJdLXOZxi2/oOivsTU19ZWJfe8elio/htRtcJtzODFwM2EpaCBBDsDf/0PIpIZIBcX8Lt7LSi3HuWLWjt14E/TPEKqMQnnFxzWBBsyje2uT4WeOJBSiX/wYgAS3hEjeugSzVNYJMfxr1M6w1R9Wg+/x0+R+s5RaMEu82n6Pwg8GX+3b16vYs9HkZl3dP7ssgJZzv9tqwKSAl1KriIw9jZQ8xJNOjZ6RvCB/R/xPaU2O5qKIhhLTR03oHLutQ4vw5mDE1QVNXRQBlyf/X7I/NlYfCDhMiHg4v9xO9Mw31l8MKgg=

cache:
  directories:
    - "node_modules"
